### ISSUE TITLE
Cannot find stage and stage_ros

### ISSUE THREAD

**Issue by YCH188** [SantoshBanisetty/master-slave#1]
Hello, I try to compile this code. But when catkin_make, I find 
cannot find a package configuration file provided by "stage" with any of
  the following names:
    stageConfig.cmake
    stage-config.cmake
Could you help me fix this problem?
Many thanks!

**Comment by SantoshBanisetty** [comment]
@YCH188 sudo apt-get install ros-<version_name>-stage*
For example, sudo apt-get install ros-indigo-stage* (If using Indigo version of ROS). 

Hope it helps!

**Comment by YCH188** [comment]
@SantoshBanisetty Tanks for your response. I'm using ros kinetic on Ubuntu 16.04. Ros kinetic has installed stage and stage_ros on default. Is the ros version matters for this problem? How could I run it on kinetic?
Hope for your help!

**Comment by YCH188** [comment]
I have solve it. I delete stage and stage_ros in CMakeLists.txt and it works.
But I found another problem. The robot stuck as the picture shows. 
![2018-10-12 16-17-00](https://user-images.githubusercontent.com/33064860/46857369-5fc5f000-ce3b-11e8-921b-4f1d278b854c.png)

**Comment by SantoshBanisetty** [comment]
> I have solve it. I delete stage and stage_ros in CMakeLists.txt and it works.
> But I found another problem. The robot stuck as the picture shows.
> ![2018-10-12 16-17-00](https://user-images.githubusercontent.com/33064860/46857369-5fc5f000-ce3b-11e8-921b-4f1d278b854c.png)
If you see the master robot code, I haven't implemented any recovery behaviors. You might consider exploring a recovery behavior for some corner cases like this. One way is to rotate 180 degree and take a step back and continue. I will leave the implementation for you to explore.

**Comment by YCH188** [comment]
@SantoshBanisetty Thanks a lot!
